### PR TITLE
Installation cleanup target

### PR DESCRIPTION
**Pull request by israpps**
## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [ ] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK
- [ ] Requires update of the gsKit
- [ ] Others (please specify below)

## Pull Request description

This will delete the following folders before installing OpenTuna
- `FORTUNA`
- `OPENTUNA`
- `APPS`

### CODE REVIEW

**Comment by parrado** [comment]
Please, don't reference SoftDev1, as it's a non publicly shared homebrew.

**Comment by israpps** [comment]
> Please, don't reference SoftDev1, as it's a non publicly shared homebrew.

done

**Review by AKuHAK — APPROVED** [review]

**Comment by israpps** [comment]
@parrado shall we merge this?

**Comment by parrado** [comment]
> @parrado shall we merge this?

I guess It's ok, anyway it would be great to add manual installation feature.

**Comment by israpps** [comment]
> > @parrado shall we merge this?
> 
> I guess It's ok, anyway it would be great to add manual installation feature.

If chelsea makes the images I can make the manual install menu

**Pull request merged**
