### PR TITLE
Add support for both Memory card ports and provisory support for Opentuna for FAT units (don't merge untill images are updated)

### PR DESCRIPTION
**Pull request by israpps**
## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [x] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK
- [ ] Requires update of the gsKit
- [ ] Others (please specify below)

## Pull Request description
Add support to Install OpenTuna to any memory card instead of going straight for port 0...
i did this because i saw some people complaining because the port 0 on their consoles was broken...

This PR is still draft, since it requires changes on the image displayed

### CODE REVIEW

**Comment by israpps** [comment]
I know that @HowlingWolfHWC is working on instatuna, but since it might take years (like some sort of 2nd XEB) then merging this ( after editing the images) should do the job for a while

**Review by parrado — COMMENTED** [review]
Please ensure icon binary files correspond to OpenTuna v1.0.2. You can find them in The Tuna's Testing discord server.

**Comment by israpps** [comment]
The icons hosted there where Taken from discord server you mentioned

**Comment by israpps** [comment]
Maybe implementing something like this:
```c
#ifdef ON_SCREEN_DEBUG
#define BDPRINTF(arg...) scr_printf(arg...);/// White text on screen
#elif HIDDEN_DEBUG
#define BDPRINTF(arg...) printf(arg...);/// no need to explain
#else
#define BDPRINTF(arg...) /// no need to explain
#endif
```

**Comment by parrado** [comment]
Well, if tests work, I'm gonna merge PR as its current  form.

> Maybe implementing something like this:
> 
> ```c
> #ifdef ON_SCREEN_DEBUG
> #define BDPRINTF(arg...) scr_printf(arg...);/// White text on screen
> #elif HIDDEN_DEBUG
> #define BDPRINTF(arg...) printf(arg...);/// no need to explain
> #else
> #define BDPRINTF(arg...) /// no need to explain
> #endif
> ```

**Comment by israpps** [comment]
maybe it´s worth adding this to the CI:
```
wget https://github.com/israpps/wLaunchELF_ISR/releases/download/latest/BOOT.ELF -O INSTALL/APPS/ULE.ELF
```

**Comment by israpps** [comment]
Ps2dev should remain permanently on 1.2.0 for this project. since it has proven to behave correctly (at least i got no reports from users of my custom installer for FunTuna based on this Project)

**Pull request merged**
